BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path = public, extensions, auth, pg_temp;
SELECT plan(14);
SELECT has_function('public','normalize_inventory_identifier',ARRAY['text'],'identifier normalization exists');
SELECT has_table('public','product_identifiers','product identifier table exists');
SELECT has_table('public','inventory_unknown_scan_events','unknown scan audit table exists');
SELECT has_function('public','resolve_inventory_identifier',ARRAY['uuid','text','text','uuid'],'exact identifier resolver exists');
SELECT has_function('public','report_unknown_inventory_scan',ARRAY['uuid','uuid','text','text','text','uuid','timestamp with time zone'],'unknown scan reporting exists');
SELECT is(public.normalize_inventory_identifier(' Ab C-123 '),'ab c-123','normalization is case/whitespace insensitive');
SELECT has_index('public','products','products_company_normalized_sku_unique_idx','normalized tenant SKU unique index exists');
SELECT has_index('public','product_identifiers','product_identifiers_company_normalized_unique_idx','tenant identifier unique index exists');
SELECT ok(NOT has_function_privilege('anon','public.resolve_inventory_identifier(uuid,text,text,uuid)','EXECUTE'),'anonymous cannot resolve transactional identifiers');
SELECT ok(has_function_privilege('authenticated','public.resolve_inventory_identifier(uuid,text,text,uuid)','EXECUTE'),'authenticated may resolve identifiers');
SELECT ok(NOT has_function_privilege('anon','public.report_unknown_inventory_scan(uuid,uuid,text,text,text,uuid,timestamp with time zone)','EXECUTE'),'anonymous cannot report unknown scans');
SELECT ok(has_function_privilege('authenticated','public.report_unknown_inventory_scan(uuid,uuid,text,text,text,uuid,timestamp with time zone)','EXECUTE'),'authenticated may report unknown scans');
SELECT throws_ok($$ INSERT INTO products(id,company_id,name,sku,base_unit_id,default_sale_unit_id) SELECT gen_random_uuid(),id,'Duplicate SKU',' MIRO-LAP-14 ',gen_random_uuid(),gen_random_uuid() FROM companies LIMIT 1 $$,'23505',NULL,'case-insensitive normalized duplicate SKU rejected');
SELECT throws_ok($$ INSERT INTO product_identifiers(company_id,product_id,identifier_type,identifier_value) SELECT company_id,id,'BARCODE',' MIRO-MON-27 ' FROM products WHERE sku='MIRO-LAP-14' LIMIT 1 $$,'23505','Identifier collides with another product SKU','cross-namespace collision rejected');
SELECT * FROM finish();
ROLLBACK;
