#!/usr/bin/env bash
set -euo pipefail

DB_URL="${PHASE11_DB_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
EVIDENCE="${PHASE11_EVIDENCE_DIR:-.phase11-evidence}/backup-restore"
mkdir -p "$EVIDENCE"
BACKUP="$EVIDENCE/inventory-balances.sql"
RESTORE_SQL="$EVIDENCE/inventory-balances.shadow-restore.sql"
SOURCE_BEFORE="$EVIDENCE/source-before.tsv"
SOURCE_AFTER_DUMP="$EVIDENCE/source-after-dump.tsv"
RESTORED="$EVIDENCE/restored.tsv"
DIFF_FILE="$EVIDENCE/restore.diff"
RESTORE_SCHEMA="phase11_restore"

cleanup() {
  psql "$DB_URL" -X -q -v ON_ERROR_STOP=1 -c "DROP SCHEMA IF EXISTS ${RESTORE_SCHEMA} CASCADE;" >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Canonical snapshot includes every inventory_balances column.  COPY produces a
# deterministic representation and the ORDER BY uses the authoritative position key.
snapshot_public() {
  psql "$DB_URL" -X -qAt -c "COPY (
    SELECT company_id, location_id, product_id, inventory_status,
           on_hand_base_qty, reserved_base_qty, physical_status_revision,
           reservation_revision, updated_at, bin_id
    FROM public.inventory_balances
    ORDER BY company_id, location_id, bin_id, product_id, inventory_status
  ) TO STDOUT WITH (FORMAT csv, HEADER false, DELIMITER E'\\t', NULL '\\N');"
}

snapshot_shadow() {
  psql "$DB_URL" -X -qAt -c "COPY (
    SELECT company_id, location_id, product_id, inventory_status,
           on_hand_base_qty, reserved_base_qty, physical_status_revision,
           reservation_revision, updated_at, bin_id
    FROM ${RESTORE_SCHEMA}.inventory_balances
    ORDER BY company_id, location_id, bin_id, product_id, inventory_status
  ) TO STDOUT WITH (FORMAT csv, HEADER false, DELIMITER E'\\t', NULL '\\N');"
}

sha256_file() {
  python3 - "$1" <<'PY'
import hashlib, pathlib, sys
p = pathlib.Path(sys.argv[1])
print(hashlib.sha256(p.read_bytes()).hexdigest())
PY
}

snapshot_public > "$SOURCE_BEFORE"
ROWS_BEFORE=$(wc -l < "$SOURCE_BEFORE" | tr -d ' ')
[[ "$ROWS_BEFORE" -gt 0 ]] || { echo 'FAIL: inventory_balances snapshot is empty' >&2; exit 1; }
HASH_BEFORE=$(sha256_file "$SOURCE_BEFORE")

# Use PostgreSQL's own backup tool. Column INSERTs make the artifact readable and
# allow an isolated restore without mutating the source database.
pg_dump "$DB_URL" \
  --data-only \
  --column-inserts \
  --table=public.inventory_balances \
  --file="$BACKUP" > "$EVIDENCE/backup.log" 2>&1
[[ -s "$BACKUP" ]] || { echo 'FAIL: pg_dump backup is empty' >&2; exit 1; }

# Prove the authoritative source did not change while the backup was produced.
snapshot_public > "$SOURCE_AFTER_DUMP"
if ! cmp -s "$SOURCE_BEFORE" "$SOURCE_AFTER_DUMP"; then
  diff -u "$SOURCE_BEFORE" "$SOURCE_AFTER_DUMP" > "$EVIDENCE/source-during-backup.diff" || true
  {
    echo 'source_unchanged_during_dump=false'
    echo "rows_before=$ROWS_BEFORE"
    echo "hash_before=$HASH_BEFORE"
    echo "hash_after_dump=$(sha256_file "$SOURCE_AFTER_DUMP")"
  } > "$EVIDENCE/source-stability.log"
  echo 'FAIL: inventory_balances changed while pg_dump was running; backup comparison would be ambiguous' >&2
  exit 1
fi
{
  echo 'source_unchanged_during_dump=true'
  echo "rows_before=$ROWS_BEFORE"
  echo "hash_before=$HASH_BEFORE"
  echo "hash_after_dump=$(sha256_file "$SOURCE_AFTER_DUMP")"
} > "$EVIDENCE/source-stability.log"

# Restore into an isolated shadow table. This validates lossless PostgreSQL
# backup/restore without TRUNCATE CASCADE or production-table trigger side effects.
psql "$DB_URL" -X -v ON_ERROR_STOP=1 <<SQL > "$EVIDENCE/restore-setup.log" 2>&1
DROP SCHEMA IF EXISTS ${RESTORE_SCHEMA} CASCADE;
CREATE SCHEMA ${RESTORE_SCHEMA};
CREATE TABLE ${RESTORE_SCHEMA}.inventory_balances
  (LIKE public.inventory_balances INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING IDENTITY);
SQL

# Re-target only the INSERT destination emitted by pg_dump.  All values remain
# exactly those generated by PostgreSQL's backup tool.
sed "s/INSERT INTO public\.inventory_balances/INSERT INTO ${RESTORE_SCHEMA}.inventory_balances/g" "$BACKUP" > "$RESTORE_SQL"
if ! grep -q "INSERT INTO ${RESTORE_SCHEMA}\.inventory_balances" "$RESTORE_SQL"; then
  echo 'FAIL: pg_dump output did not contain restorable inventory_balances INSERT statements' >&2
  exit 1
fi
psql "$DB_URL" -X -v ON_ERROR_STOP=1 -f "$RESTORE_SQL" > "$EVIDENCE/restore.log" 2>&1

snapshot_shadow > "$RESTORED"
ROWS_AFTER=$(wc -l < "$RESTORED" | tr -d ' ')
HASH_AFTER=$(sha256_file "$RESTORED")

{
  echo "rows_before=$ROWS_BEFORE"
  echo "rows_after=$ROWS_AFTER"
  echo "hash_before=$HASH_BEFORE"
  echo "hash_after=$HASH_AFTER"
} > "$EVIDENCE/reconciliation.log"

if ! cmp -s "$SOURCE_BEFORE" "$RESTORED"; then
  diff -u "$SOURCE_BEFORE" "$RESTORED" > "$DIFF_FILE" || true
  echo 'Match: False' >> "$EVIDENCE/reconciliation.log"
  echo "FAIL: inventory balance pg_dump/shadow-restore mismatch; inspect $DIFF_FILE" >&2
  exit 1
fi

echo 'Match: True' >> "$EVIDENCE/reconciliation.log"
echo 'PASS Phase 11 backup/restore proof: pg_dump round-trip reproduced every inventory_balances row exactly.'
